name: deploy-command
on:
  workflow_dispatch:
    inputs:
      repository-name:
        description: "The name of the repository from which the slash command was dispatched"
        required: true
      repository-owner:
        description: "The owner of the repository from which the slash command was dispatched"
        required: true
      issue-number:
        description: "The issue number in which the slash command was made"
        required: true
      html-url:
        description: "URL where comment was created"
        required: true
      comment-id:
        description: "ID of comment with deploy command"
        required: true
      cluster:
        description: "The cluster to deploy to"
        required: true
      commit:
        description: "Commit ID to deploy"
        required: false
      branch:
        description: "Branch to deploy"
        required: false
      actor:
        description: "User issuing the command"
        required: false
jobs:
  prepare-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: download and setup path for github actions binary
        run: |
          mkdir -p github-actions/bin
          curl -L -o github-actions/bin/actions https://github.com/dictybase-docker/github-actions/releases/download/v0.5.1/action_0.5.1_Linux_x86_64
          chmod +x github-actions/bin/actions
          echo "::add-path::$GITHUB_WORKSPACE/github-actions/bin"
      - name: parse deploy command and set vars
        id: vars
        run: actions --log-level debug pcd -f ${GITHUB_EVENT_PATH} --frontend
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.event.inputs.repository-owner }}/${{ github.event.inputs.repository-name }}
          ref: ${{ steps.vars.outputs.ref }}
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ steps.vars.outputs.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build and push (ericdev)
        if: github.event.inputs.cluster == 'erickube'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: dictybase/${{ github.event.inputs.repository-name }}:${{ steps.vars.outputs.image_tag }}
          build-args: |
            func_server=https://ericfunc.dictybase.dev
            graphql_server=https://ericgraphql.dictybase.dev
            client_keys=https://raw.githubusercontent.com/dictybase-playground/client-keys/2.0.0/clientConfig.eric.js
            ga_tracking_id=-UA-146763741-1
            deploy_env=development
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: docker build and push (devsidd)
        if: github.event.inputs.cluster == 'siddkube'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: dictybase/${{ github.event.inputs.repository-name }}:${{ steps.vars.outputs.image_tag }}
          build-args: |
            func_server=https://siddfunc.dictybase.dev
            graphql_server=https://siddgraphql.dictybase.dev
            client_keys=https://raw.githubusercontent.com/dictybase-playground/client-keys/2.0.1/clientConfig.sidd.js
            deploy_env=development
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: prepare for deploy
        if: ${{ success() }}
        id: prepare_deploy
        uses: dictybase-docker/prepare-deploy@v2
        with:
          owner: ${{ github.event.inputs.repository-owner }}
          repo: ${{ github.event.inputs.repository-name }}
          cluster-name: ${{ github.event.inputs.cluster }}
          cluster-zone: "us-central1-a"
          namespace: dictybase
          chart-name: ${{ github.event.inputs.repository-name }}
          chart-path: dictybase/${{ github.event.inputs.repository-name }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          image-tag: ${{ steps.vars.outputs.image_tag }}
          ref: ${{ steps.vars.outputs.ref }}
          artifact: ${{ github.event.inputs.repository-name }}
          environment: ${{ github.event.inputs.cluster }}
  deploy:
    runs-on: ubuntu-latest
    needs: prepare-deploy
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: download deployment artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.inputs.repository-name }}
      - name: download and setup path for github action binary
        run: |
          mkdir -p github-actions/bin
          curl -L -o github-actions/bin/actions https://github.com/dictybase-docker/github-actions/releases/download/v0.5.1/action_0.5.1_Linux_x86_64
          chmod +x github-actions/bin/actions
          echo "::add-path::$GITHUB_WORKSPACE/github-actions/bin"
      - name: extract information from deployment payload
        id: deploy_info
        run: actions --log-level debug sdp -f deployment.json
      - name: set in_progress deployment status
        if: ${{ success() }}
        run: actions --log-level debug -t ${{ secrets.REPO_ACCESS_TOKEN }} --owner ${{ github.event.inputs.repository-owner }} -r ${{ github.event.inputs.repository-name }} ds --state in_progress  --deployment_id ${{ steps.deploy_info.outputs.id }} --url ${{ steps.deploy_info.outputs.url }}
      - name: set up google cloud sdk
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "307.0.0"
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true
      - name: set up helm
        uses: azure/setup-helm@v1
        with:
          version: "v2.16.9"
      - name: add dictybase helm repo
        run: helm init --client-only && helm repo add dictybase https://dictybase-docker.github.io/kubernetes-charts
      - name: get gcloud credentials for k8s cluster
        run: gcloud container clusters get-credentials --project ${{ secrets.PROJECT_ID }} --zone ${{ steps.deploy_info.outputs.zone }} ${{ steps.deploy_info.outputs.cluster }}
      - name: deploy chart
        if: ${{ success() }}
        run: actions --log-level debug dc --name ${{ steps.deploy_info.outputs.chart }} --namespace ${{ steps.deploy_info.outputs.namespace }} --image-tag ${{ steps.deploy_info.outputs.image_tag }} --path ${{ steps.deploy_info.outputs.path }}
      - name: set successful deploy status
        if: ${{ success() }}
        run: actions --log-level debug -t ${{ secrets.REPO_ACCESS_TOKEN }} --owner ${{ github.event.inputs.repository-owner }} -r ${{ github.event.inputs.repository-name }} ds --state success  --deployment_id ${{ steps.deploy_info.outputs.id }} --url ${{ steps.deploy_info.outputs.url }}
      - name: set unsuccessful deploy status
        if: ${{ failure() }}
        run: actions --log-level debug -t ${{ secrets.REPO_ACCESS_TOKEN }} --owner ${{ github.event.inputs.repository-owner }} -r ${{ github.event.inputs.repository-name }} ds --state error  --deployment_id ${{ steps.deploy_info.outputs.id }} --url ${{ steps.deploy_info.outputs.url }}
  add-reaction:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.inputs.repository-owner }}/${{ github.event.inputs.repository-name }}
          comment-id: ${{ github.event.inputs.comment-id }}
          reaction-type: hooray
